export type TweetSchema = {
	id: number;
	user: string;
	handle: string;
	text: string;
	sentiment: "Positive" | "Negative" | "Neutral";
	confidence: number;
	entity: string;
	timestamp: string;
};

const tweetData: TweetSchema[] = [
	{
		id: 1,
		user: "John Doe",
		handle: "@johndoe",
		text: "Just got the new iPhone 16 — the camera is absolutely incredible. Best upgrade I have made in years.",
		sentiment: "Positive",
		confidence: 97,
		entity: "Apple",
		timestamp: "2024-06-30T14:32:00Z",
	},
	{
		id: 2,
		user: "Jane Smith",
		handle: "@janesmith",
		text: "Tesla autopilot nearly ran a red light today. Third time this month. I am genuinely scared.",
		sentiment: "Negative",
		confidence: 94,
		entity: "Tesla",
		timestamp: "2024-06-30T14:31:15Z",
	},
	{
		id: 3,
		user: "Dev Guy",
		handle: "@devguy42",
		text: "Google Cloud just updated their pricing tiers. Will need to review what this means for our stack.",
		sentiment: "Neutral",
		confidence: 88,
		entity: "Google",
		timestamp: "2024-06-30T14:30:50Z",
	},
	{
		id: 4,
		user: "Tech Enthusiast",
		handle: "@techenthusiast",
		text: "Microsoft Copilot just wrote an entire API module for me in under a minute. This is the future.",
		sentiment: "Positive",
		confidence: 96,
		entity: "Microsoft",
		timestamp: "2024-06-30T14:30:22Z",
	},
	{
		id: 5,
		user: "Angry Customer",
		handle: "@angrycustomer99",
		text: "Amazon delivery is three days late again. Customer support gave me a bot. Absolutely unacceptable.",
		sentiment: "Negative",
		confidence: 98,
		entity: "Amazon",
		timestamp: "2024-06-30T14:29:47Z",
	},
	{
		id: 6,
		user: "Investor Pro",
		handle: "@investorpro",
		text: "Apple stock is consolidating nicely above the 200 MA. Watching for a breakout this week.",
		sentiment: "Positive",
		confidence: 91,
		entity: "Apple",
		timestamp: "2024-06-30T14:29:10Z",
	},
	{
		id: 7,
		user: "Startup Founder",
		handle: "@startupfounder",
		text: "Running our entire ML pipeline on Google Vertex AI now. Deployment is fairly straightforward.",
		sentiment: "Neutral",
		confidence: 85,
		entity: "Google",
		timestamp: "2024-06-30T14:28:33Z",
	},
	{
		id: 8,
		user: "Crypto Watcher",
		handle: "@cryptowatcher",
		text: "Tesla should have held their Bitcoin. Bad timing on the sale, cost them billions in unrealized gains.",
		sentiment: "Negative",
		confidence: 89,
		entity: "Tesla",
		timestamp: "2024-06-30T14:27:55Z",
	},
	{
		id: 9,
		user: "Open Source Dev",
		handle: "@ossdev",
		text: "Microsoft acquiring more open source tooling. Mixed feelings about what this means long term.",
		sentiment: "Neutral",
		confidence: 82,
		entity: "Microsoft",
		timestamp: "2024-06-30T14:27:18Z",
	},
	{
		id: 10,
		user: "Prime Member",
		handle: "@primemember",
		text: "Amazon Prime Day deals are actually solid this year. Got a great deal on a Kindle.",
		sentiment: "Positive",
		confidence: 93,
		entity: "Amazon",
		timestamp: "2024-06-30T14:26:40Z",
	},
	{
		id: 11,
		user: "Market Analyst",
		handle: "@marketanalyst",
		text: "Apple's Services revenue grew 14% YoY. This is what the bull case has always been about.",
		sentiment: "Positive",
		confidence: 95,
		entity: "Apple",
		timestamp: "2024-06-30T14:26:03Z",
	},
	{
		id: 12,
		user: "EV Skeptic",
		handle: "@evskeptic",
		text: "Tesla's delivery numbers missed estimates again. The growth story is running out of road.",
		sentiment: "Negative",
		confidence: 92,
		entity: "Tesla",
		timestamp: "2024-06-30T14:25:22Z",
	},
	{
		id: 13,
		user: "Cloud Architect",
		handle: "@cloudarchitect",
		text: "Comparing Google Cloud Run vs AWS Lambda. Both work well. It comes down to your existing ecosystem.",
		sentiment: "Neutral",
		confidence: 80,
		entity: "Google",
		timestamp: "2024-06-30T14:24:45Z",
	},
	{
		id: 14,
		user: "Dev Advocate",
		handle: "@devadvocate",
		text: "GitHub Copilot X is a huge step up from the original. The chat interface is incredibly useful in reviews.",
		sentiment: "Positive",
		confidence: 97,
		entity: "Microsoft",
		timestamp: "2024-06-30T14:24:08Z",
	},
	{
		id: 15,
		user: "Small Business",
		handle: "@smallbizowner",
		text: "Amazon seller fees have increased again without notice. Hard to stay profitable on the platform.",
		sentiment: "Negative",
		confidence: 96,
		entity: "Amazon",
		timestamp: "2024-06-30T14:23:30Z",
	},
];

export default tweetData;
